#!/bin/bash
R='\033[1;31m'
G='\033[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[1;37m'
Green='\033[32m'
Gren='\033[32m'
Gris='\033[90m'
printf "$Gris"
echo $(clear)
echo -e $W"_____________________________________________________________________"
echo -e "          $W  ___ $Gris          _,.---,---.,_"
echo -e "           $W |  $Gris       ,;~'             '~;,"
echo -e "          $W  | $Gris      ,;                     ;,"
echo -e $R"   Frontal$W  | $Gris     ;                      $Gris  ;$W ,---$R Supraorbital Foramen"
echo -e $R"    Bone$W    |$Gris     ,'                  $W      /'"
echo -e $W"            |$Gris    ,;                   $W    /'$Gris ;,"
echo -e $W"            |$Gris    ; ;      .          .$W <-'$Gris  ; |"
echo -e $W"            |__ $Gris | ;   ______       ______   ;$W<-----$R Coronal Suture"
echo -e $W"           ___ $Gris  |  '/~"     ~" . "~     "~\'  |"
echo -e $W"           |    $Gris |  ~  ,-~~~^~, | ,~^~~~-,  ~  |"
echo -e $R" Maxilla,$W  |$Gris      |   |        }:{        |$W <------$R Orbit"
echo -e $R"Nasal and$W  |$Gris      |   l       / | \       !   |"
echo -e $R"Zygomatic$W  |$Gris      .~  (__,.--" .^. "--.,__)  ~."
echo -e $R"  Bones  $W  |$Gris      |    ----;' / | \  ;$W-<---------$R Infraorbital Foramen"
echo -e $W"           |__$Gris     \__.       \/^\/       .__"
echo -e $W"              ___$Gris   V| \                 / |V$W <---$R Mastoid Process"
echo -e $W"              | $Gris     | |T~\___!___!___/~T| |"
echo -e $W"              |$Gris      | | IIII_I_I_I_IIII | |"
echo -e $R"     Mandible$W |$Gris      |  \ III I I I III,/  |"
echo -e $W"              |$Gris       \    ~~~~~~~~~~     "
echo -e $W"              |$Gris         \   .       .$W <-x----$R Mental Foramen"
echo -e $W"              |__  $Gris       \.    ^    ."
echo "                            ^~~~^~~~^"
echo -e $W"  _________________________________________________________________"
echo -e $W"                    Created by @CesarHackGray"
echo -e $W"                      Usage:$G show options"
echo
